# Generated by Django 5.1.6 on 2025-03-20 12:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=4)),
                ('VIN', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='childs', to='api.folder', verbose_name='parent')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('assembly_disignation', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('link', models.TextField()),
                ('folder', models.ManyToManyField(related_name='details', to='api.folder', verbose_name='parent is folder')),
            ],
        ),
        migrations.CreateModel(
            name='Count_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(verbose_name='')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='api.detail')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='api.folder')),
            ],
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IMG', to='api.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), size=2)),
                ('text', models.TextField(verbose_name='')),
                ('folder_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_points', to='api.folder')),
                ('IMG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_points', to='api.img')),
            ],
        ),
    ]
