# Generated by Django 5.1.6 on 2025-03-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(blank=True, to='api.folder', verbose_name='parent'),
        ),
    ]
