# Generated by Django 5.1.6 on 2025-02-25 08:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('assembly_disignation', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=4)),
                ('VIN', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.folder', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), size=2)),
                ('text', models.TextField(verbose_name='')),
                ('detail_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detail', verbose_name='')),
                ('folder_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.folder', verbose_name='')),
                ('IMG', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.img', verbose_name='')),
            ],
        ),
    ]
