# Generated by Django 5.1.6 on 2025-02-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot_point',
            name='detail_link',
        ),
        migrations.AddField(
            model_name='detail',
            name='folder',
            field=models.ManyToManyField(to='api.folder', verbose_name='parent is folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='VIN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.AlterField(
            model_name='hot_point',
            name='folder_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.folder'),
        ),
        migrations.CreateModel(
            name='Count_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(verbose_name='')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.detail', verbose_name='')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.folder', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(to='api.folder', verbose_name='parent'),
        ),
    ]
