# Generated by Django 5.1.6 on 2025-03-11 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_details',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='api.detail'),
        ),
        migrations.AlterField(
            model_name='count_details',
            name='folder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='count_details', to='api.folder'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='folder',
            field=models.ManyToManyField(related_name='details', to='api.folder', verbose_name='parent is folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='childs', to='api.folder', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='hot_point',
            name='IMG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_points', to='api.img'),
        ),
        migrations.AlterField(
            model_name='hot_point',
            name='folder_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_points', to='api.folder'),
        ),
        migrations.AlterField(
            model_name='img',
            name='folder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IMG', to='api.folder'),
        ),
    ]
