# Generated by Django 5.1.6 on 2025-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='childs', to='api.folder', verbose_name='parent'),
        ),
    ]
